# fly.toml app configuration file generated for contacts-backend-0ywb5g on 2025-11-15T14:11:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'contacts-backend-0ywb5g'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = "production"
  MONGO_URI=mongodb://localhost:27017/contacts_app
  JWT_SECRET=3d88f@5!zA%TYk79^uP0kj9k#r3
  NODE_ENV=development
  MONGO_INITDB_ROOT_USERNAME=root
  MONGO_INITDB_ROOT_PASSWORD=example
  MONGO_INITDB_DATABASE=contacts_app
  PORT=3000
  API_COMMAND=npm start
  MONGO_PORT=27018
  MONGO_URL=mongodb://root:example@mongo:27017/contacts_app?authSource=admin

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
